#include <stdio.h>
#include "hal_data.h"
#include "RTT/SEGGER_RTT.h"

#define UART_BUFFER_SIZE 1024

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void system_init(void);
int _write(int file, char *buffer, int count);

volatile bool transmitComplete;
static int r;

void User_Button_Callback(external_irq_callback_args_t *p_args)
{
    bsp_io_level_t button_status;

    if(p_args->channel ==1)
    {
        R_IOPORT_PinRead(&g_ioport_ctrl, BUTTON, &button_status);
        if(BSP_IO_LEVEL_LOW == button_status)
        {
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, BSP_IO_LEVEL_HIGH);
        }
        else
        {
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, BSP_IO_LEVEL_LOW);
        }
    }
}

void user_uart_callback(uart_callback_args_t *p_args)
{
    switch(p_args->event)
   {
       case UART_EVENT_TX_COMPLETE:
           transmitComplete = true;
           break;
       case UART_EVENT_RX_CHAR:
           break;
       default:
           break;
   }
}

void system_init(void)
{
    R_ICU_ExternalIrqOpen(&g_external_irq1_ctrl, &g_external_irq1_cfg);
    R_ICU_ExternalIrqEnable(&g_external_irq1_ctrl);

    R_SCI_UART_Open(&g_uart9_ctrl, &g_uart9_cfg);
    // Disable Output Buffering
    setvbuf ( stdout, NULL, _IONBF, UART_BUFFER_SIZE);

}

int _write(int file, char *buffer, int count)
{
    (void)file;
    int tx_count;
    int i;

    for(i=0, tx_count=0; i<count; i++, tx_count++)
    {
        transmitComplete = false;
        R_SCI_UART_Write(&g_uart9_ctrl, (uint8_t const*)(buffer+i), 1);
        while(!transmitComplete){};
    }

    return tx_count;
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    system_init();
    int i = 0;

    printf("Application Start\r\n");

    SEGGER_RTT_WriteString(0, "SEGGER RTT Terminal\r\n");
    SEGGER_RTT_ConfigUpBuffer(0, NULL, NULL, 0, SEGGER_RTT_MODE_NO_BLOCK_SKIP);

    while(1)
    {
        i++;
        printf("Loop %d\r\n", i);
//        SEGGER_RTT_printf(0, "RTT Printf %d\r\n", i);
//        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        r = SEGGER_RTT_WaitKey();
        SEGGER_RTT_Write(0, &r, 1);
        r++;
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
