#include "hal_data.h"

#include <stdio.h>
#include "RTT/SEGGER_RTT.h"

#define SET_FLAG                             (0x01)
#define RESET_FLAG                           (0x00)

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void set_every10s_alarm(void);
void init_rtc(void);

volatile uint32_t g_alarm_irq_flag = RESET_FLAG;       //flag to check occurrence of alarm interrupt
volatile uint32_t g_periodic_irq_flag = RESET_FLAG;    //flag to check occurrence of periodic interrupt


void rtc_callback(rtc_callback_args_t *p_args)
{
    if(RTC_EVENT_ALARM_IRQ == p_args->event)
    {
        g_alarm_irq_flag = SET_FLAG;
    }
    else
    {
        g_periodic_irq_flag = SET_FLAG;
    }
}

void set_every10s_alarm(void)
{
    rtc_alarm_time_t alarm_time;

    alarm_time.dayofweek_match = false;
    alarm_time.year_match = false;
    alarm_time.mon_match = false;
    alarm_time.mday_match  = false;
    alarm_time.hour_match = false;
    alarm_time.min_match = false;
    alarm_time.sec_match = true;

    alarm_time.time.tm_sec = 10;

    R_RTC_CalendarAlarmSet(&g_rtc_ctrl, &alarm_time);
}

void init_rtc(void)
{
    rtc_time_t set_time =  {
                               .tm_hour    =  RESET_FLAG,
                               .tm_isdst   =  RESET_FLAG,
                               .tm_mday    =  RESET_FLAG,
                               .tm_min     =  RESET_FLAG,
                               .tm_mon     =  RESET_FLAG,
                               .tm_sec     =  RESET_FLAG,
                               .tm_wday    =  RESET_FLAG,
                               .tm_yday    =  RESET_FLAG,
                               .tm_year    =  RESET_FLAG,
                              };

       // initializes RTC module
       R_RTC_Open(&g_rtc_ctrl, &g_rtc_cfg);

       set_time.tm_year = 2022 - 1900;
       set_time.tm_mon = 1;
       set_time.tm_mday = 20;
       set_time.tm_hour = 10;
       set_time.tm_min = 12;
       set_time.tm_sec = 30;

       // sets the Calendar time
       R_RTC_CalendarTimeSet(&g_rtc_ctrl, &set_time);
       R_RTC_PeriodicIrqRateSet(&g_rtc_ctrl, RTC_PERIODIC_IRQ_SELECT_1_SECOND);
       set_every10s_alarm();
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
   rtc_time_t get_time =  {
                           .tm_hour    =  RESET_FLAG,
                           .tm_isdst   =  RESET_FLAG,
                           .tm_mday    =  RESET_FLAG,
                           .tm_min     =  RESET_FLAG,
                           .tm_mon     =  RESET_FLAG,
                           .tm_sec     =  RESET_FLAG,
                           .tm_wday    =  RESET_FLAG,
                           .tm_yday    =  RESET_FLAG,
                           .tm_year    =  RESET_FLAG,
                          };

   init_rtc();

    while(1)
    {
        if(SET_FLAG == g_periodic_irq_flag)
        {
            R_RTC_CalendarTimeGet(&g_rtc_ctrl, &get_time);
            SEGGER_RTT_printf(0, "\r\n RTC calendar get to  Date : %d/%d/%d \n Time : %d:%d:%d \r\n\n",
                    (get_time.tm_year + 1900), get_time.tm_mon, get_time.tm_mday,
                    get_time.tm_hour, get_time.tm_min, get_time.tm_sec);

            g_periodic_irq_flag = RESET_FLAG;
        }

        if(SET_FLAG == g_alarm_irq_flag)
        {
            SEGGER_RTT_printf(0, "every 10S timer alarm\r\n");
            g_alarm_irq_flag = RESET_FLAG;
        }

        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
