#include "hal_data.h"
#include "ST7735.h"
#include "GFX_FUNCTIONS.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    ST7735_Init(0);
    fillScreen(BLACK);
    testAll();
    R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);

    while(1)
    {
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);

        ST7735_SetRotation(0);
        ST7735_WriteString(0, 0, "HELLO", Font_11x18, RED,BLACK);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        fillScreen(BLACK);

        ST7735_SetRotation(1);
        ST7735_WriteString(0, 0, "WORLD", Font_11x18, GREEN,BLACK);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        fillScreen(BLACK);

        ST7735_SetRotation(2);
        ST7735_WriteString(0, 0, "FROM", Font_11x18, BLUE,BLACK);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        fillScreen(BLACK);

        ST7735_SetRotation(3);
        ST7735_WriteString(0, 0, "ControllersTech", Font_16x26, YELLOW,BLACK);
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);
        fillScreen(BLACK);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
